const jobs = [
    {
      name: 'Product Manager 1',
      description: 'Description for Product Manager 1',
      jobLocation: 'Onsite',
      jobType: 'FullTime',
      jobTag: 'Product Manager',
    },
    {
      name: 'Product Manager 2',
      description: 'Description for Product Manager 2',
      jobLocation: 'Remote',
      jobType: 'PartTime',
      jobTag: 'Product Manager',
    },
    {
      name: 'Product Manager 2',
      description: 'Description for Product Manager 2',
      jobLocation: 'Remote',
      jobType: 'PartTime',
      jobTag: 'Product Manager',
    },
    {
      name: 'Product Manager 2',
      description: 'Description for Product Manager 2',
      jobLocation: 'Remote',
      jobType: 'PartTime',
      jobTag: 'Product Manager',
    },
    {
      name: 'Product Manager 2',
      description: 'Description for Product Manager 2',
      jobLocation: 'Remote',
      jobType: 'PartTime',
      jobTag: 'Product Manager',
    },
    {
      name: 'Architect 1',
      description: 'Description for Architect 1',
      jobLocation: 'Onsite',
      jobType: 'Intern',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 1',
      description: 'Description for Architect 1',
      jobLocation: 'Onsite',
      jobType: 'Intern',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 1',
      description: 'Description for Architect 1',
      jobLocation: 'Onsite',
      jobType: 'Intern',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 1',
      description: 'Description for Architect 1',
      jobLocation: 'Onsite',
      jobType: 'Intern',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 2',
      description: 'Description for Architect 2',
      jobLocation: 'Remote',
      jobType: 'RecentJob',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 2',
      description: 'Description for Architect 2',
      jobLocation: 'Remote',
      jobType: 'RecentJob',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 2',
      description: 'Description for Architect 2',
      jobLocation: 'Remote',
      jobType: 'RecentJob',
      jobTag: 'Architect',
    },
    {
      name: 'Architect 2',
      description: 'Description for Architect 2',
      jobLocation: 'Remote',
      jobType: 'RecentJob',
      jobTag: 'Architect',
    },
    {
      name: 'IT Related Job 1',
      description: 'Description for IT Related Job 1',
      jobLocation: 'Onsite',
      jobType: 'FullTime',
      jobTag: 'IT Related',
    },
    {
      name: 'IT Related Job 2',
      description: 'Description for IT Related Job 2',
      jobLocation: 'Remote',
      jobType: 'PartTime',
      jobTag: 'IT Related',
    }
  ];

export default jobs;